[package]
name = "rustlib"
version = "0.12.3"

[dependencies]
rustr = "*"
rayon = ">= 1.5.0"
roots = "*"

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
