[package]
name = "rustlib"
version = "0.13.0"

[dependencies]
rayon = ">= 1.5.0"
roots = "*"
extendr-api = ">= 0.2.0"

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
