// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_perform_filtering_for_r(SEXP update_type, SEXP q, SEXP alpha, SEXP delta_t, SEXP first_aprils);
SEXP baseflow_perform_filtering_for_r(SEXP update_type, SEXP q, SEXP alpha, SEXP delta_t, SEXP first_aprils){ return(rustr_perform_filtering_for_r(update_type,q,alpha,delta_t,first_aprils));}
extern SEXP rustr_bfi_for_r(SEXP update_type, SEXP q, SEXP alpha, SEXP delta_t, SEXP first_aprils);
SEXP baseflow_bfi_for_r(SEXP update_type, SEXP q, SEXP alpha, SEXP delta_t, SEXP first_aprils){ return(rustr_bfi_for_r(update_type,q,alpha,delta_t,first_aprils));}
extern SEXP rustr_criteria_for_r(SEXP update_type, SEXP q, SEXP alpha, SEXP delta_t, SEXP p, SEXP pet, SEXP tau, SEXP first_aprils);
SEXP baseflow_criteria_for_r(SEXP update_type, SEXP q, SEXP alpha, SEXP delta_t, SEXP p, SEXP pet, SEXP tau, SEXP first_aprils){ return(rustr_criteria_for_r(update_type,q,alpha,delta_t,p,pet,tau,first_aprils));}
extern SEXP rustr_criteria_vector_for_r(SEXP update_type, SEXP q, SEXP alphas, SEXP delta_t, SEXP p, SEXP pet, SEXP taus, SEXP first_aprils);
SEXP baseflow_criteria_vector_for_r(SEXP update_type, SEXP q, SEXP alphas, SEXP delta_t, SEXP p, SEXP pet, SEXP taus, SEXP first_aprils){ return(rustr_criteria_vector_for_r(update_type,q,alphas,delta_t,p,pet,taus,first_aprils));}
